<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE root [
<!ELEMENT root (Table*)>
<!ELEMENT Table (Row*)>
<!ELEMENT Row (Item*)>
<!ELEMENT Item (#PCDATA)>
<!ATTLIST Table name CDATA #REQUIRED>
<!ATTLIST Item name CDATA #REQUIRED>
]>
<root>
<Table name="Table1">
<Row>
<Item name="objid">1237661086422532537</Item>
<Item name="ra">130.9465742027</Item>
<Item name="dec">27.8351176931385</Item>
<Item name="u">24.59545</Item>
<Item name="g">21.82903</Item>
<Item name="r">20.15928</Item>
<Item name="i">19.29787</Item>
<Item name="z">18.81742</Item>
<Item name="specobjid">5014760202102396928</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4917254</Item>
</Row>
<Row>
<Item name="objid">1237657609112191434</Item>
<Item name="ra">130.946839648769</Item>
<Item name="dec">43.9753188344164</Item>
<Item name="u">22.31659</Item>
<Item name="g">21.7451</Item>
<Item name="r">20.04281</Item>
<Item name="i">19.45121</Item>
<Item name="z">19.05732</Item>
<Item name="specobjid">7187900418055493632</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4493994</Item>
</Row>
<Row>
<Item name="objid">1237667430089491338</Item>
<Item name="ra">130.947079860851</Item>
<Item name="dec">16.7942456889042</Item>
<Item name="u">26.0292</Item>
<Item name="g">22.51282</Item>
<Item name="r">20.91419</Item>
<Item name="i">19.95291</Item>
<Item name="z">19.77439</Item>
<Item name="specobjid">5951706298492147712</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4924225</Item>
</Row>
<Row>
<Item name="objid">1237653664713671240</Item>
<Item name="ra">130.947439157389</Item>
<Item name="dec">1.28526995594271</Item>
<Item name="u">25.03445</Item>
<Item name="g">21.41306</Item>
<Item name="r">19.54985</Item>
<Item name="i">18.77792</Item>
<Item name="z">18.26519</Item>
<Item name="specobjid">4289772204475045888</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4352329</Item>
</Row>
<Row>
<Item name="objid">1237661068166103276</Item>
<Item name="ra">130.947644897274</Item>
<Item name="dec">7.8528602432703</Item>
<Item name="u">23.47459</Item>
<Item name="g">21.39774</Item>
<Item name="r">19.88511</Item>
<Item name="i">19.07451</Item>
<Item name="z">18.87223</Item>
<Item name="specobjid">5950412168625412096</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.3149834</Item>
</Row>
<Row>
<Item name="objid">1237667253993865627</Item>
<Item name="ra">130.94842195115</Item>
<Item name="dec">18.608943289305</Item>
<Item name="u">22.79396</Item>
<Item name="g">20.68582</Item>
<Item name="r">19.01898</Item>
<Item name="i">18.36938</Item>
<Item name="z">17.93084</Item>
<Item name="specobjid">5827773470910732288</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.2841455</Item>
</Row>
<Row>
<Item name="objid">1237651252022935970</Item>
<Item name="ra">130.948501468398</Item>
<Item name="dec">52.4636664442396</Item>
<Item name="u">23.05687</Item>
<Item name="g">21.92311</Item>
<Item name="r">20.05513</Item>
<Item name="i">19.21054</Item>
<Item name="z">18.77774</Item>
<Item name="specobjid">5806478399582263296</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.491578</Item>
</Row>
<Row>
<Item name="objid">1237653664713671246</Item>
<Item name="ra">130.949266361514</Item>
<Item name="dec">1.31936557739418</Item>
<Item name="u">22.4737</Item>
<Item name="g">22.17178</Item>
<Item name="r">20.54499</Item>
<Item name="i">19.62847</Item>
<Item name="z">19.00156</Item>
<Item name="specobjid">4289770830085511168</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4636132</Item>
</Row>
<Row>
<Item name="objid">1237657609112191468</Item>
<Item name="ra">130.949411339075</Item>
<Item name="dec">43.994179904377</Item>
<Item name="u">22.29032</Item>
<Item name="g">21.13498</Item>
<Item name="r">20.11172</Item>
<Item name="i">19.54623</Item>
<Item name="z">19.16681</Item>
<Item name="specobjid">7187911138293864448</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4543692</Item>
</Row>
<Row>
<Item name="objid">1237660343393649213</Item>
<Item name="ra">130.949524123217</Item>
<Item name="dec">32.3440232405415</Item>
<Item name="u">25.73458</Item>
<Item name="g">21.41553</Item>
<Item name="r">19.61054</Item>
<Item name="i">18.91896</Item>
<Item name="z">18.58804</Item>
<Item name="specobjid">5837964290355910656</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4256765</Item>
</Row>
<Row>
<Item name="objid">1237651701915386222</Item>
<Item name="ra">130.949583095043</Item>
<Item name="dec">54.6623857428776</Item>
<Item name="u">25.6117</Item>
<Item name="g">21.93819</Item>
<Item name="r">20.67748</Item>
<Item name="i">20.06072</Item>
<Item name="z">19.33365</Item>
<Item name="specobjid">8302399495339268096</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.3519322</Item>
</Row>
<Row>
<Item name="objid">1237651701915386599</Item>
<Item name="ra">130.949748594362</Item>
<Item name="dec">54.7766554077477</Item>
<Item name="u">25.55551</Item>
<Item name="g">22.63908</Item>
<Item name="r">21.22474</Item>
<Item name="i">20.70003</Item>
<Item name="z">19.94231</Item>
<Item name="specobjid">8302398395827640320</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4255287</Item>
</Row>
<Row>
<Item name="objid">1237674370756969016</Item>
<Item name="ra">130.950341462048</Item>
<Item name="dec">22.4498711853846</Item>
<Item name="u">27.01541</Item>
<Item name="g">21.9992</Item>
<Item name="r">20.35541</Item>
<Item name="i">19.4375</Item>
<Item name="z">19.07234</Item>
<Item name="specobjid">5035056093228980224</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.48753</Item>
</Row>
<Row>
<Item name="objid">1237663547979006305</Item>
<Item name="ra">130.950840002315</Item>
<Item name="dec">58.6594054885248</Item>
<Item name="u">25.46275</Item>
<Item name="g">21.15612</Item>
<Item name="r">19.27595</Item>
<Item name="i">18.5411</Item>
<Item name="z">18.12134</Item>
<Item name="specobjid">5796334035409328128</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.3535447</Item>
</Row>
<Row>
<Item name="objid">1237658491184218962</Item>
<Item name="ra">130.951140143684</Item>
<Item name="dec">4.65331254250464</Item>
<Item name="u">23.67117</Item>
<Item name="g">22.46152</Item>
<Item name="r">21.06051</Item>
<Item name="i">20.19176</Item>
<Item name="z">19.82154</Item>
<Item name="specobjid">4288803251766450176</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4746067</Item>
</Row>
<Row>
<Item name="objid">1237660343393649032</Item>
<Item name="ra">130.951448853104</Item>
<Item name="dec">32.2331865790628</Item>
<Item name="u">21.90388</Item>
<Item name="g">21.02777</Item>
<Item name="r">19.21217</Item>
<Item name="i">18.4212</Item>
<Item name="z">18.08489</Item>
<Item name="specobjid">1361244093438519296</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4092033</Item>
</Row>
<Row>
<Item name="objid">1237667430626427587</Item>
<Item name="ra">130.95146344415</Item>
<Item name="dec">17.2580208903662</Item>
<Item name="u">23.8117</Item>
<Item name="g">22.82944</Item>
<Item name="r">21.9082</Item>
<Item name="i">21.84441</Item>
<Item name="z">20.98319</Item>
<Item name="specobjid">10761424008333514752</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.2994439</Item>
</Row>
<Row>
<Item name="objid">1237651250411733295</Item>
<Item name="ra">130.951599236321</Item>
<Item name="dec">50.6930697843247</Item>
<Item name="u">25.1541</Item>
<Item name="g">20.17597</Item>
<Item name="r">18.4287</Item>
<Item name="i">17.83599</Item>
<Item name="z">17.49292</Item>
<Item name="specobjid">501190416712886272</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.3534536</Item>
</Row>
<Row>
<Item name="objid">1237660412646851475</Item>
<Item name="ra">130.951826046084</Item>
<Item name="dec">6.19458951201996</Item>
<Item name="u">24.21776</Item>
<Item name="g">23.00876</Item>
<Item name="r">21.28789</Item>
<Item name="i">20.2478</Item>
<Item name="z">20.05849</Item>
<Item name="specobjid">5520309058043926528</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4133357</Item>
</Row>
<Row>
<Item name="objid">1237667210507387496</Item>
<Item name="ra">130.952320191968</Item>
<Item name="dec">17.8609286477455</Item>
<Item name="u">24.80873</Item>
<Item name="g">21.74101</Item>
<Item name="r">19.87268</Item>
<Item name="i">19.04645</Item>
<Item name="z">18.64034</Item>
<Item name="specobjid">5951711796050286592</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4638775</Item>
</Row>
<Row>
<Item name="objid">1237650796750242588</Item>
<Item name="ra">130.95271905899</Item>
<Item name="dec">0.577553809613306</Item>
<Item name="u">23.50623</Item>
<Item name="g">22.04738</Item>
<Item name="r">20.62085</Item>
<Item name="i">20.05101</Item>
<Item name="z">19.73948</Item>
<Item name="specobjid">14108773103657310208</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.2644616</Item>
</Row>
<Row>
<Item name="objid">1237660962936587101</Item>
<Item name="ra">130.952929628335</Item>
<Item name="dec">31.198051581511</Item>
<Item name="u">25.66106</Item>
<Item name="g">22.32685</Item>
<Item name="r">20.38324</Item>
<Item name="i">19.51565</Item>
<Item name="z">18.91854</Item>
<Item name="specobjid">5837884850640803840</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4352694</Item>
</Row>
<Row>
<Item name="objid">1237674370756968853</Item>
<Item name="ra">130.953057749053</Item>
<Item name="dec">22.5194113263061</Item>
<Item name="u">24.64305</Item>
<Item name="g">21.28823</Item>
<Item name="r">20.02024</Item>
<Item name="i">19.27641</Item>
<Item name="z">18.99916</Item>
<Item name="specobjid">5035056642984794112</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4867683</Item>
</Row>
<Row>
<Item name="objid">1237657773930184840</Item>
<Item name="ra">130.953169396397</Item>
<Item name="dec">36.3040302158475</Item>
<Item name="u">23.76595</Item>
<Item name="g">20.03286</Item>
<Item name="r">18.53359</Item>
<Item name="i">17.95052</Item>
<Item name="z">17.60727</Item>
<Item name="specobjid">5189389873501722624</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.2819471</Item>
</Row>
<Row>
<Item name="objid">1237664669499130634</Item>
<Item name="ra">130.953445662553</Item>
<Item name="dec">27.0796818823252</Item>
<Item name="u">22.81516</Item>
<Item name="g">22.25099</Item>
<Item name="r">20.88918</Item>
<Item name="i">20.0766</Item>
<Item name="z">19.68809</Item>
<Item name="specobjid">5833421388556556288</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4675247</Item>
</Row>
<Row>
<Item name="objid">1237664669499130244</Item>
<Item name="ra">130.953579906592</Item>
<Item name="dec">27.0330258906553</Item>
<Item name="u">22.04243</Item>
<Item name="g">21.53775</Item>
<Item name="r">21.06139</Item>
<Item name="i">20.49482</Item>
<Item name="z">20.15706</Item>
<Item name="specobjid">12523650062407194624</Item>
<Item name="class">QSO</Item>
<Item name="redshift">0.4670133</Item>
</Row>
<Row>
<Item name="objid">1237648722819875604</Item>
<Item name="ra">130.953616161057</Item>
<Item name="dec">1.10406474903403</Item>
<Item name="u">22.66202</Item>
<Item name="g">21.49661</Item>
<Item name="r">20.05856</Item>
<Item name="i">19.31391</Item>
<Item name="z">18.92545</Item>
<Item name="specobjid">4289769730573883392</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4641215</Item>
</Row>
<Row>
<Item name="objid">1237663530799006038</Item>
<Item name="ra">130.954057773122</Item>
<Item name="dec">58.3873850644749</Item>
<Item name="u">22.69901</Item>
<Item name="g">22.68552</Item>
<Item name="r">20.67149</Item>
<Item name="i">19.73691</Item>
<Item name="z">19.24637</Item>
<Item name="specobjid">5796207866450040832</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4124599</Item>
</Row>
<Row>
<Item name="objid">1237660764838167124</Item>
<Item name="ra">130.954024335229</Item>
<Item name="dec">30.5122189612623</Item>
<Item name="u">23.59744</Item>
<Item name="g">20.94329</Item>
<Item name="r">19.15173</Item>
<Item name="i">18.5595</Item>
<Item name="z">18.26587</Item>
<Item name="specobjid">5835734480741226496</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.3352696</Item>
</Row>
<Row>
<Item name="objid">1237653665787413100</Item>
<Item name="ra">130.954498851316</Item>
<Item name="dec">2.10419337230983</Item>
<Item name="u">22.26448</Item>
<Item name="g">21.74702</Item>
<Item name="r">20.49315</Item>
<Item name="i">20.00252</Item>
<Item name="z">19.70228</Item>
<Item name="specobjid">14108812686075910144</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.3385607</Item>
</Row>
<Row>
<Item name="objid">1237671260123759059</Item>
<Item name="ra">130.954552307877</Item>
<Item name="dec">9.55815612169097</Item>
<Item name="u">22.19407</Item>
<Item name="g">20.16768</Item>
<Item name="r">18.45929</Item>
<Item name="i">17.85205</Item>
<Item name="z">17.43395</Item>
<Item name="specobjid">1981678170939615232</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.3226015</Item>
</Row>
<Row>
<Item name="objid">1237651192431968584</Item>
<Item name="ra">130.955219259865</Item>
<Item name="dec">52.8150140663892</Item>
<Item name="u">22.77787</Item>
<Item name="g">20.73602</Item>
<Item name="r">19.01605</Item>
<Item name="i">18.40195</Item>
<Item name="z">17.95932</Item>
<Item name="specobjid">5806466030076450816</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.2920204</Item>
</Row>
<Row>
<Item name="objid">1237658298985087417</Item>
<Item name="ra">130.955242094734</Item>
<Item name="dec">4.02441358367786</Item>
<Item name="u">23.89662</Item>
<Item name="g">20.63015</Item>
<Item name="r">18.93702</Item>
<Item name="i">18.18224</Item>
<Item name="z">17.74409</Item>
<Item name="specobjid">1337605142794496000</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4354398</Item>
</Row>
<Row>
<Item name="objid">1237658492258025566</Item>
<Item name="ra">130.95576592072</Item>
<Item name="dec">5.67508754281169</Item>
<Item name="u">24.67833</Item>
<Item name="g">23.48776</Item>
<Item name="r">21.26498</Item>
<Item name="i">20.18008</Item>
<Item name="z">19.89259</Item>
<Item name="specobjid">5520304110241601536</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4975205</Item>
</Row>
<Row>
<Item name="objid">1237664092899573851</Item>
<Item name="ra">130.955929411686</Item>
<Item name="dec">25.7612188153786</Item>
<Item name="u">23.88788</Item>
<Item name="g">21.53317</Item>
<Item name="r">19.66529</Item>
<Item name="i">18.8794</Item>
<Item name="z">18.47669</Item>
<Item name="specobjid">5832349083952764928</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4431236</Item>
</Row>
<Row>
<Item name="objid">1237657608575124037</Item>
<Item name="ra">130.956135372731</Item>
<Item name="dec">43.3466740429335</Item>
<Item name="u">24.31836</Item>
<Item name="g">21.49523</Item>
<Item name="r">20.08146</Item>
<Item name="i">19.54752</Item>
<Item name="z">19.29146</Item>
<Item name="specobjid">7187869631729915904</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.2633817</Item>
</Row>
<Row>
<Item name="objid">1237660962399584542</Item>
<Item name="ra">130.957640976496</Item>
<Item name="dec">30.906858327336</Item>
<Item name="u">24.90837</Item>
<Item name="g">20.95071</Item>
<Item name="r">19.10221</Item>
<Item name="i">18.52138</Item>
<Item name="z">18.12724</Item>
<Item name="specobjid">5837887324541966336</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.3360728</Item>
</Row>
<Row>
<Item name="objid">1237664285097263784</Item>
<Item name="ra">130.958094966711</Item>
<Item name="dec">7.88718126944328</Item>
<Item name="u">22.83997</Item>
<Item name="g">22.17567</Item>
<Item name="r">20.51626</Item>
<Item name="i">19.59401</Item>
<Item name="z">19.2499</Item>
<Item name="specobjid">5950412718381225984</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4792541</Item>
</Row>
<Row>
<Item name="objid">1237650796750242297</Item>
<Item name="ra">130.958242621984</Item>
<Item name="dec">0.609230295110833</Item>
<Item name="u">23.71634</Item>
<Item name="g">21.41704</Item>
<Item name="r">19.82714</Item>
<Item name="i">19.29251</Item>
<Item name="z">18.86176</Item>
<Item name="specobjid">14108775302680565760</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.263382</Item>
</Row>
<Row>
<Item name="objid">1237667538536039077</Item>
<Item name="ra">130.958734175137</Item>
<Item name="dec">15.9198760896309</Item>
<Item name="u">23.5457</Item>
<Item name="g">21.40077</Item>
<Item name="r">20.0151</Item>
<Item name="i">19.22473</Item>
<Item name="z">18.74304</Item>
<Item name="specobjid">5951577655631697920</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.478533</Item>
</Row>
<Row>
<Item name="objid">1237661068166169177</Item>
<Item name="ra">130.958832782595</Item>
<Item name="dec">7.86120467264076</Item>
<Item name="u">22.17637</Item>
<Item name="g">20.85813</Item>
<Item name="r">19.0159</Item>
<Item name="i">18.30911</Item>
<Item name="z">17.89243</Item>
<Item name="specobjid">1461520383390803968</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4199733</Item>
</Row>
<Row>
<Item name="objid">1237658190539194912</Item>
<Item name="ra">130.95892970189</Item>
<Item name="dec">33.4582187158771</Item>
<Item name="u">22.75139</Item>
<Item name="g">21.19289</Item>
<Item name="r">19.42806</Item>
<Item name="i">18.76181</Item>
<Item name="z">18.36501</Item>
<Item name="specobjid">5839051713378801664</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.3980272</Item>
</Row>
<Row>
<Item name="objid">1237663548516073728</Item>
<Item name="ra">130.959260354275</Item>
<Item name="dec">59.3560455854691</Item>
<Item name="u">22.69162</Item>
<Item name="g">20.76502</Item>
<Item name="r">18.88908</Item>
<Item name="i">18.20721</Item>
<Item name="z">17.84521</Item>
<Item name="specobjid">2009815520827697152</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.3255082</Item>
</Row>
<Row>
<Item name="objid">1237663786886169074</Item>
<Item name="ra">130.960042503625</Item>
<Item name="dec">60.4042255739727</Item>
<Item name="u">25.75896</Item>
<Item name="g">22.04237</Item>
<Item name="r">20.31356</Item>
<Item name="i">19.37978</Item>
<Item name="z">18.84217</Item>
<Item name="specobjid">6427885273955457024</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4942144</Item>
</Row>
<Row>
<Item name="objid">1237667142326157798</Item>
<Item name="ra">130.960146716417</Item>
<Item name="dec">20.4156704809716</Item>
<Item name="u">23.25976</Item>
<Item name="g">21.38197</Item>
<Item name="r">19.46028</Item>
<Item name="i">18.86684</Item>
<Item name="z">18.55614</Item>
<Item name="specobjid">5827813877963053056</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.3275214</Item>
</Row>
<Row>
<Item name="objid">1237664668425191849</Item>
<Item name="ra">130.960916417139</Item>
<Item name="dec">25.998073582527</Item>
<Item name="u">23.49784</Item>
<Item name="g">21.50536</Item>
<Item name="r">19.61346</Item>
<Item name="i">18.91367</Item>
<Item name="z">18.59961</Item>
<Item name="specobjid">5832348534196951040</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4246684</Item>
</Row>
<Row>
<Item name="objid">1237658203956314584</Item>
<Item name="ra">130.960979946116</Item>
<Item name="dec">34.3223226310122</Item>
<Item name="u">22.82202</Item>
<Item name="g">21.11379</Item>
<Item name="r">19.41489</Item>
<Item name="i">18.76158</Item>
<Item name="z">18.19422</Item>
<Item name="specobjid">5000128725926565888</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.3099509</Item>
</Row>
<Row>
<Item name="objid">1237663531336073793</Item>
<Item name="ra">130.961405489143</Item>
<Item name="dec">59.133504475098</Item>
<Item name="u">23.43643</Item>
<Item name="g">22.41574</Item>
<Item name="r">20.39889</Item>
<Item name="i">19.39157</Item>
<Item name="z">18.97383</Item>
<Item name="specobjid">5796332111263979520</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4824107</Item>
</Row>
<Row>
<Item name="objid">1237664092362572570</Item>
<Item name="ra">130.961356292313</Item>
<Item name="dec">25.2715410196421</Item>
<Item name="u">26.31561</Item>
<Item name="g">20.61825</Item>
<Item name="r">19.43243</Item>
<Item name="i">18.69465</Item>
<Item name="z">18.27026</Item>
<Item name="specobjid">5832352107609741312</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.267842</Item>
</Row>
<Row>
<Item name="objid">1237657773930120055</Item>
<Item name="ra">130.96142858956</Item>
<Item name="dec">36.0957617396829</Item>
<Item name="u">22.61604</Item>
<Item name="g">21.42217</Item>
<Item name="r">19.5243</Item>
<Item name="i">18.91676</Item>
<Item name="z">18.55664</Item>
<Item name="specobjid">5189397570083117056</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.3373803</Item>
</Row>
<Row>
<Item name="objid">1237650795139629914</Item>
<Item name="ra">130.961723771879</Item>
<Item name="dec">-0.756986026255043</Item>
<Item name="u">25.65806</Item>
<Item name="g">22.2304</Item>
<Item name="r">20.47756</Item>
<Item name="i">19.86867</Item>
<Item name="z">19.38928</Item>
<Item name="specobjid">14101928643774404608</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4207903</Item>
</Row>
<Row>
<Item name="objid">1237663787960304055</Item>
<Item name="ra">130.962199479566</Item>
<Item name="dec">61.5638086634178</Item>
<Item name="u">21.51786</Item>
<Item name="g">20.33977</Item>
<Item name="r">18.60809</Item>
<Item name="i">18.01459</Item>
<Item name="z">17.53744</Item>
<Item name="specobjid">6427940799292659712</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.3609444</Item>
</Row>
<Row>
<Item name="objid">1237661124540564068</Item>
<Item name="ra">130.962533466363</Item>
<Item name="dec">27.5711521818898</Item>
<Item name="u">23.20816</Item>
<Item name="g">21.81503</Item>
<Item name="r">20.48204</Item>
<Item name="i">19.65769</Item>
<Item name="z">19.38486</Item>
<Item name="specobjid">5833432658550740992</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4953133</Item>
</Row>
<Row>
<Item name="objid">1237661124540564086</Item>
<Item name="ra">130.962657822582</Item>
<Item name="dec">27.5797140875014</Item>
<Item name="u">24.46358</Item>
<Item name="g">21.35407</Item>
<Item name="r">19.70705</Item>
<Item name="i">18.70959</Item>
<Item name="z">18.1994</Item>
<Item name="specobjid">5014761851369838592</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4945427</Item>
</Row>
<Row>
<Item name="objid">1237667142863094392</Item>
<Item name="ra">130.962711949665</Item>
<Item name="dec">20.90047483466</Item>
<Item name="u">22.06204</Item>
<Item name="g">20.71306</Item>
<Item name="r">18.9157</Item>
<Item name="i">18.12744</Item>
<Item name="z">17.64507</Item>
<Item name="specobjid">2567158776847165440</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4227692</Item>
</Row>
<Row>
<Item name="objid">1237651250411733335</Item>
<Item name="ra">130.963275026561</Item>
<Item name="dec">50.6910912919218</Item>
<Item name="u">25.80836</Item>
<Item name="g">20.36106</Item>
<Item name="r">18.65644</Item>
<Item name="i">18.01541</Item>
<Item name="z">17.64677</Item>
<Item name="specobjid">4162723073966233600</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.3555088</Item>
</Row>
<Row>
<Item name="objid">1237651252560068625</Item>
<Item name="ra">130.963387256276</Item>
<Item name="dec">53.3399329471728</Item>
<Item name="u">23.66498</Item>
<Item name="g">21.30885</Item>
<Item name="r">19.58161</Item>
<Item name="i">18.82994</Item>
<Item name="z">18.48075</Item>
<Item name="specobjid">8192155867669616640</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.3208706</Item>
</Row>
<Row>
<Item name="objid">1237660669807428169</Item>
<Item name="ra">130.963422131183</Item>
<Item name="dec">7.1761980392797</Item>
<Item name="u">25.20548</Item>
<Item name="g">22.06852</Item>
<Item name="r">20.64064</Item>
<Item name="i">19.60278</Item>
<Item name="z">19.1177</Item>
<Item name="specobjid">5950418765695178752</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4988746</Item>
</Row>
<Row>
<Item name="objid">1237651252560069060</Item>
<Item name="ra">130.963514028674</Item>
<Item name="dec">53.3346970516737</Item>
<Item name="u">21.90544</Item>
<Item name="g">20.31433</Item>
<Item name="r">18.77095</Item>
<Item name="i">18.15467</Item>
<Item name="z">17.791</Item>
<Item name="specobjid">5806459982762498048</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.3611424</Item>
</Row>
<Row>
<Item name="objid">1237658300058895367</Item>
<Item name="ra">130.963738635856</Item>
<Item name="dec">4.91552503626345</Item>
<Item name="u">22.1701</Item>
<Item name="g">21.16498</Item>
<Item name="r">19.41504</Item>
<Item name="i">18.71007</Item>
<Item name="z">18.31725</Item>
<Item name="specobjid">4288812322737379328</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4170435</Item>
</Row>
<Row>
<Item name="objid">1237658300595765742</Item>
<Item name="ra">130.96387025246</Item>
<Item name="dec">5.28121230547991</Item>
<Item name="u">24.62659</Item>
<Item name="g">20.43594</Item>
<Item name="r">18.67821</Item>
<Item name="i">18.04655</Item>
<Item name="z">17.6687</Item>
<Item name="specobjid">5520298887561369600</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.2894368</Item>
</Row>
<Row>
<Item name="objid">1237671124832617286</Item>
<Item name="ra">130.964049194441</Item>
<Item name="dec">10.9330921602851</Item>
<Item name="u">24.1744</Item>
<Item name="g">21.55239</Item>
<Item name="r">19.82949</Item>
<Item name="i">19.02437</Item>
<Item name="z">18.5884</Item>
<Item name="specobjid">2897063948618590208</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4587361</Item>
</Row>
<Row>
<Item name="objid">1237667782812042183</Item>
<Item name="ra">130.964177187596</Item>
<Item name="dec">13.7424728193367</Item>
<Item name="u">25.32411</Item>
<Item name="g">21.54764</Item>
<Item name="r">19.83212</Item>
<Item name="i">19.0329</Item>
<Item name="z">18.70743</Item>
<Item name="specobjid">5953921258626504704</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4489151</Item>
</Row>
<Row>
<Item name="objid">1237667253993931143</Item>
<Item name="ra">130.964775807208</Item>
<Item name="dec">18.6657010451163</Item>
<Item name="u">23.31137</Item>
<Item name="g">20.03802</Item>
<Item name="r">18.39142</Item>
<Item name="i">17.80558</Item>
<Item name="z">17.45037</Item>
<Item name="specobjid">2566016384735668224</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.2839165</Item>
</Row>
<Row>
<Item name="objid">1237667255604740774</Item>
<Item name="ra">130.965123284513</Item>
<Item name="dec">19.946683062296</Item>
<Item name="u">23.73117</Item>
<Item name="g">21.96889</Item>
<Item name="r">20.28335</Item>
<Item name="i">19.45927</Item>
<Item name="z">19.06189</Item>
<Item name="specobjid">5827828171614214144</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.457762</Item>
</Row>
<Row>
<Item name="objid">1237664092362637894</Item>
<Item name="ra">130.965357828328</Item>
<Item name="dec">25.3655336021053</Item>
<Item name="u">24.71554</Item>
<Item name="g">21.44333</Item>
<Item name="r">19.54147</Item>
<Item name="i">18.75347</Item>
<Item name="z">18.33555</Item>
<Item name="specobjid">5832348809074857984</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4497807</Item>
</Row>
<Row>
<Item name="objid">1237648722283004993</Item>
<Item name="ra">130.965983517465</Item>
<Item name="dec">0.799754105649237</Item>
<Item name="u">25.58086</Item>
<Item name="g">22.1481</Item>
<Item name="r">20.5013</Item>
<Item name="i">19.64508</Item>
<Item name="z">19.04462</Item>
<Item name="specobjid">4289768081306441728</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4838906</Item>
</Row>
<Row>
<Item name="objid">1237664668425126126</Item>
<Item name="ra">130.921067089989</Item>
<Item name="dec">26.0140271115107</Item>
<Item name="u">25.31898</Item>
<Item name="g">21.73758</Item>
<Item name="r">19.78403</Item>
<Item name="i">18.84624</Item>
<Item name="z">18.50265</Item>
<Item name="specobjid">5832347709563230208</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4758595</Item>
</Row>
<Row>
<Item name="objid">1237655108362895868</Item>
<Item name="ra">130.921126827944</Item>
<Item name="dec">45.7439897382863</Item>
<Item name="u">23.35054</Item>
<Item name="g">21.78125</Item>
<Item name="r">20.52439</Item>
<Item name="i">19.88309</Item>
<Item name="z">19.40192</Item>
<Item name="specobjid">7201321056900241408</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.4570321</Item>
</Row>
<Row>
<Item name="objid">1237648722819875522</Item>
<Item name="ra">130.921162546013</Item>
<Item name="dec">1.14472199970631</Item>
<Item name="u">22.60235</Item>
<Item name="g">21.10338</Item>
<Item name="r">19.42619</Item>
<Item name="i">18.83433</Item>
<Item name="z">18.48361</Item>
<Item name="specobjid">14108768155854985216</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.3414698</Item>
</Row>
<Row>
<Item name="objid">1237664874583360000</Item>
<Item name="ra">130.921168961093</Item>
<Item name="dec">24.0676763767705</Item>
<Item name="u">24.70312</Item>
<Item name="g">21.04351</Item>
<Item name="r">19.30384</Item>
<Item name="i">18.6404</Item>
<Item name="z">18.17754</Item>
<Item name="specobjid">5832245180103940096</Item>
<Item name="class">GALAXY</Item>
<Item name="redshift">0.3697445</Item>
</Row>
<Row>
<Item name="objid">1237671261734502926</Item>
<Item name="ra">130.921604672508</Item>
<Item name="dec">10.9083171795348</Item>
<Item name="u">23.32913</Item>